/*
Update vanilla BG2 files or older mod files
Any other minor updates can go here as well.
This is run with every component.
*/


//bg2 engine, check glow effect
ACTION_IF (GAME_IS ~bg2 tob tutu tutu_totsc iwd_in_bg2 ca~) BEGIN
  LAF dknightglow255 END
END

//check item restrictions
COPY_EXISTING_REGEXP GLOB ~^d2tec.*\.itm~  ~override~
  LPF d2_no_usableflags END
  LPF DELETE_EFFECT INT_VAR match_opcode=319 END
  LPF fixstackcharges END
BUT_ONLY


//update bg2 files
ACTION_PHP_EACH update_items AS mod => base BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~%base%.ITM~) BEGIN
    COPY_EXISTING ~%mod%.ITM~  ~override/%base%.ITM~
      LPF ALTER_EFFECT INT_VAR silent=1 STR_VAR match_resource=~%SOURCE_RES%~ resource=~%DEST_RES%~ END
    IF_EXISTS
  END
END


//copy to old iwd2 resource (so old items work)
ACTION_DEFINE_ASSOCIATIVE_ARRAY d2mira_iwd2oldres BEGIN    // icon res
  ~%bigmetalrod%~  => d2mira01
  ~%pulse%~        => d2mira02
  ~%frag%~         => d2mira03
  ~%scorcher%~     => d2mira04
  ~%bigmetalunit%~ => d2mira05
  ~%prototype%~    => d2mira06
  ~%pulseIII%~     => d2mira07
END

ACTION_IF (GAME_IS ~iwd2~) BEGIN
  ACTION_PHP_EACH d2mira_iwd2oldres AS item => res BEGIN
    COPY_EXISTING ~%item%.itm~  ~override/%res%.itm~
      LPF ALTER_EFFECT INT_VAR silent=1 STR_VAR match_resource=~%SOURCE_RES%~ resource=~%DEST_RES%~ END
    IF_EXISTS
  END
END


/*
*/