//
//


//bg2: copy base files to mod (account for possible changes NOT added to mod files)
//this is skipped if for some reason the base files no longer include changes from this mod
ACTION_PHP_EACH update_items AS mod => base BEGIN
  ACTION_IF (RESOURCE_CONTAINS ~%base%.itm~  ~d2tec~) BEGIN
    COPY_EXISTING ~%base%.itm~  ~override/%mod%.itm~
      LPF ALTER_EFFECT INT_VAR silent=1 STR_VAR match_resource=~%SOURCE_RES%~ resource=~%DEST_RES%~ END
    IF_EXISTS
  END
END

//bgee/iwdee: check for forgotten armaments crit immunity tweak
ACTION_IF ((FILE_EXISTS ~engine.lua~) && !(FILE_EXISTS_IN_GAME ~secret05.itm~)) BEGIN
  OUTER_SET CritImmunity1 = ID_OF_LABEL ~forgotten-armament.tp2~ ~ForgottenArmament-CritImmunity1~
  OUTER_SET CritImmunity2 = ID_OF_LABEL ~forgotten-armament.tp2~ ~ForgottenArmament-CritImmunity2~

  OUTER_SET fa_check = 0
  ACTION_IF (MOD_IS_INSTALLED ~forgotten-armament.tp2~ CritImmunity1) BEGIN  OUTER_SET fa_check = 1  END
  ACTION_IF (MOD_IS_INSTALLED ~forgotten-armament.tp2~ CritImmunity2) BEGIN  OUTER_SET fa_check = 1  END

  COPY_EXISTING ~d2tec05.itm~  ~override~
    PATCH_IF (fa_check > 0) BEGIN
      WRITE_LONG 0x18 THIS | BIT25
    END ELSE BEGIN
      WRITE_LONG 0x18 (THIS BAND BNOT BIT25)
    END
  BUT_ONLY
END


//update icons for Pulse variants
DEFINE_ACTION_FUNCTION pulseicons STR_VAR item=~~ bam=~~ BEGIN
  COPY ~%icons%/%bam%.bam~  ~override/%item%.bam~
  COPY_EXISTING ~%item%.itm~  ~override~
    WRITE_ASCII 0x3a ~%item%~ #8
    LPF ALTER_ITEM_HEADER STR_VAR icon=~%item%~ END
  BUT_ONLY
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~%prototype%.bam~) BEGIN
  LAF pulseicons STR_VAR item=~%prototype%~ bam=prototypeicon END
  LAF pulseicons STR_VAR item=~%pulseIII%~ bam=pulse3icon END
  COPY_EXISTING ~%prototype%b.itm~  ~override~
    WRITE_ASCII 0x3a ~%prototype%~ #8
    LPF ALTER_ITEM_HEADER STR_VAR icon=~%prototype%~ END
  IF_EXISTS BUT_ONLY
END


//
INCLUDE ~%install%/copyskull.tph~    // check skull proj
INCLUDE ~%install%/updatebg2.tph~    // Update BG2 files


/*
*/