/*
Update vanilla BG2 files
This does nothing if ToB is not part of the game.
*/


//
//Update BG2 files
ACTION_PHP_EACH update_items AS mod => base BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~%base%.ITM~) BEGIN
    ACTION_IF (FILE_EXISTS ~override/%mod%.ITM~) BEGIN
      COPY_EXISTING ~%mod%.ITM~  ~override/%base%.ITM~
        LPF ALTER_EFFECT INT_VAR silent=1 STR_VAR match_resource=~%SOURCE_RES%~ resource=~%DEST_RES%~ END
    END
  END
END


/*
*/