//
//


//variable if tweak is installed later
ACTION_IF (MOD_IS_INSTALLED ~d2-mira.tp2~ 0) BEGIN  
  OUTER_SET mira = 1
END ELSE BEGIN
  OUTER_SET mira = 2
END


//BG2 item array
ACTION_IF (FILE_EXISTS_IN_GAME ~secret05.itm~) BEGIN

ACTION_DEFINE_ASSOCIATIVE_ARRAY update_items BEGIN    // mod => base
  d2tec01 => secret01
  d2tec02 => secret02
  d2tec03 => secret03
  d2tec04 => secret04
  d2tec05 => secret05
  d2pant01 => MISCCB
  d2pant02 => MISC5O
  d2pant03 => MISC47
END

END


//BG1 ARE files (used in bg1scripts.tph)
OUTER_TEXT_SPRINT baldursgate ~AR0800~
OUTER_TEXT_SPRINT candlekeep  ~AR2600~
OUTER_TEXT_SPRINT luckystore  ~AR0810~
OUTER_TEXT_SPRINT thiefguild  ~AR0153~

ACTION_IF (GAME_IS ~eet~) BEGIN
  OUTER_TEXT_SPRINT baldursgate ~BG0800~
  OUTER_TEXT_SPRINT candlekeep  ~BG2600~
  OUTER_TEXT_SPRINT luckystore  ~BG0810~
  OUTER_TEXT_SPRINT thiefguild  ~BG0153~
END
ACTION_IF (GAME_IS ~tutu tutu_totsc~) BEGIN    // note: tutu uses different names for the area scripts
  OUTER_TEXT_SPRINT baldursgate ~FW0800~
  OUTER_TEXT_SPRINT candlekeep  ~FW2600~
  OUTER_TEXT_SPRINT luckystore  ~FW0810~
  OUTER_TEXT_SPRINT thiefguild  ~FW0153~
END
ACTION_IF (GAME_IS ~bgt~) BEGIN
  OUTER_TEXT_SPRINT baldursgate ~AR7800~
  OUTER_TEXT_SPRINT candlekeep  ~AR0015~
  OUTER_TEXT_SPRINT luckystore  ~AR7810~
  OUTER_TEXT_SPRINT thiefguild  ~AR7253~
END


//iwd Journal entries
ACTION_IF (GAME_IS ~iwd how totlm~) BEGIN
  OUTER_TEXT_SPRINT iwdjour01  ~@10001~
  OUTER_TEXT_SPRINT iwdjour02  ~@10002~
  OUTER_TEXT_SPRINT iwdjour03  ~@10003~
  OUTER_TEXT_SPRINT iwdjour04  ~@10004~
END ELSE BEGIN
  OUTER_TEXT_SPRINT iwdjour01  ~@10001,INFO~
  OUTER_TEXT_SPRINT iwdjour02  ~@10002,INFO~
  OUTER_TEXT_SPRINT iwdjour03  ~@10003,INFO~
  OUTER_TEXT_SPRINT iwdjour04  ~@10004,INFO~
END

//bg1 journal entries
ACTION_IF (GAME_IS ~bg1 totsc~) BEGIN
  OUTER_TEXT_SPRINT bg1jour01  ~@30001~
  OUTER_TEXT_SPRINT bg1jour02  ~@30002~
  OUTER_TEXT_SPRINT bg1jour03  ~@30003~
  OUTER_TEXT_SPRINT bg1jour04  ~@30004~
END ELSE BEGIN
  OUTER_TEXT_SPRINT bg1jour01  ~@30001,INFO~
  OUTER_TEXT_SPRINT bg1jour02  ~@30002,INFO~
  OUTER_TEXT_SPRINT bg1jour03  ~@30003,INFO~
  OUTER_TEXT_SPRINT bg1jour04  ~@30004,INFO~
END


//add missing entry, used for a check later
ACTION_IF (GAME_IS ~bg2 tob tutu tutu_totsc iwd_in_bg2 ca~) BEGIN
  ACTION_IF !(RESOURCE_CONTAINS ~stats.ids~  ~NPC_BUMP~) BEGIN
    APPEND ~stats.ids~  ~190 NPC_BUMP~
  END
END


//
//functions

//sets stacks to 1 if ammo charges installed
OUTER_SET nostacks = 0
ACTION_IF (MOD_IS_INSTALLED ~d2-mira.tp2~ 61) BEGIN  OUTER_SET nostacks = 1  END
ACTION_IF (MOD_IS_INSTALLED ~d2-mira.tp2~ 62) BEGIN  OUTER_SET nostacks = 1  END
ACTION_IF (MOD_IS_INSTALLED ~d2-mira.tp2~ 63) BEGIN  OUTER_SET nostacks = 1  END

DEFINE_PATCH_FUNCTION fixstackcharges BEGIN
  PATCH_IF (nostacks > 0) BEGIN
    READ_SHORT 0x1c type
    PATCH_IF (type = 31) BEGIN  WRITE_SHORT 0x38 1  END    // 31 = bolts
  END
END


//bg2 engine: check glow effect (255 crashes BG2 without IA, does not crash EEs/IWD1/IWD2)
OUTER_SET glow255 = 0
ACTION_IF (MOD_IS_INSTALLED ~setup-infinityanimations.tp2~ 0) BEGIN  OUTER_SET glow255 = 1  END

DEFINE_ACTION_FUNCTION dknightglow255 BEGIN
  ACTION_IF (MOD_IS_INSTALLED ~d2-mira.tp2~ 71) BEGIN    // if demon knight animation installed
    COPY_EXISTING ~%bigmetalunit%.itm~  ~override~
      PATCH_IF (glow255 > 0) BEGIN
        LPF ALTER_EFFECT INT_VAR silent=1 match_opcode=8 parameter2=255 END
      END ELSE BEGIN
        LPF ALTER_EFFECT INT_VAR silent=1 match_opcode=8 parameter2=3 END
      END
    BUT_ONLY
  END
END



//
//Set item variables

OUTER_TEXT_SPRINT bigmetalrod  ~d2tec01~
OUTER_TEXT_SPRINT pulse        ~d2tec02~
OUTER_TEXT_SPRINT frag         ~d2tec03~
OUTER_TEXT_SPRINT scorcher     ~d2tec04~
OUTER_TEXT_SPRINT bigmetalunit ~d2tec05~
OUTER_TEXT_SPRINT prototype    ~d2tec06~
OUTER_TEXT_SPRINT pulseIII     ~d2tec07~
OUTER_TEXT_SPRINT metalrodb    ~d2tec01b~    // for BG1 (different text)
OUTER_TEXT_SPRINT prototypeb   ~d2tec06b~    // for BG1 (different text)
OUTER_TEXT_SPRINT brokenrod    ~d2tec50~     // for BG2 (malfunctioned rod)
OUTER_TEXT_SPRINT repairbook   ~d2tec55~     // for BG2 (repair manual)

/*old iwd2 resource
ACTION_IF (GAME_IS ~iwd2~) BEGIN
  OUTER_TEXT_SPRINT bigmetalrod  ~d2mira01~
  OUTER_TEXT_SPRINT pulse        ~d2mira02~
  OUTER_TEXT_SPRINT frag         ~d2mira03~
  OUTER_TEXT_SPRINT scorcher     ~d2mira04~
  OUTER_TEXT_SPRINT bigmetalunit ~d2mira05~
  OUTER_TEXT_SPRINT prototype    ~d2mira06~
  OUTER_TEXT_SPRINT pulseIII     ~d2mira07~
END
*/

OUTER_TEXT_SPRINT bronze  ~d2pant01~
OUTER_TEXT_SPRINT silver  ~d2pant02~
OUTER_TEXT_SPRINT gold    ~d2pant03~
OUTER_TEXT_SPRINT mirabag ~d2#mbag~
OUTER_TEXT_SPRINT metalrod ~%bigmetalrod%~
OUTER_TEXT_SPRINT metalunit ~%bigmetalunit%~
OUTER_TEXT_SPRINT checkbag  ~%mirabag%t~


/*
*/